ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'FREE';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'STARTER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'PRO';

UPDATE "User" SET "role" = 'FREE' WHERE "role" = 'USER';
UPDATE "User" SET "role" = 'STARTER' WHERE "role" = 'SUBSCRIBED';
